#!perl

# AUTHORITY
# DATE
# DIST
# VERSION

# NO_PERINCI_CMDLINE_SCRIPT
# FRAGMENT id=shcompgen-hint completer=1 for=cpanm-allperls

use 5.010001;
use strict;
use warnings;
use App::ShellCompleter::cpanm;

App::ShellCompleter::cpanm::run_completer();

# ABSTRACT: Shell completer for cpanm-allperls
# PODNAME:
